steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/website-repo/website:$COMMIT_SHA",
        ".",
      ]

  # Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/website-repo/website:$COMMIT_SHA",
      ]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "website"
      - "--image"
      - "europe-west1-docker.pkg.dev/$PROJECT_ID/website-repo/website:$COMMIT_SHA"
      - "--region"
      - "europe-west1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/website-repo/website:$COMMIT_SHA"
